package br.ufsc.das.sumservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-23T11:17:03.437-02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "SumService", 
                  wsdlLocation = "file:/D:/Work/workspace_devstudio/sumService/src/SumService.wsdl",
                  targetNamespace = "http://das.ufsc.br/SumService/") 
public class SumService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://das.ufsc.br/SumService/", "SumService");
    public final static QName SumServiceSOAP = new QName("http://das.ufsc.br/SumService/", "SumServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Work/workspace_devstudio/sumService/src/SumService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SumService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Work/workspace_devstudio/sumService/src/SumService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SumService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SumService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SumService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SumService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SumService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SumService
     */
    @WebEndpoint(name = "SumServiceSOAP")
    public SumService getSumServiceSOAP() {
        return super.getPort(SumServiceSOAP, SumService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SumService
     */
    @WebEndpoint(name = "SumServiceSOAP")
    public SumService getSumServiceSOAP(WebServiceFeature... features) {
        return super.getPort(SumServiceSOAP, SumService.class, features);
    }

}
