package br.ufsc.das.sumservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-23T11:17:03.404-02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://das.ufsc.br/SumService/", name = "SumService")
@XmlSeeAlso({ObjectFactory.class})
public interface SumService {

    @WebMethod(action = "http://das.ufsc.br/SumService/sum")
    @RequestWrapper(localName = "sum", targetNamespace = "http://das.ufsc.br/SumService/", className = "br.ufsc.das.sumservice.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://das.ufsc.br/SumService/", className = "br.ufsc.das.sumservice.SumResponse")
    @WebResult(name = "result", targetNamespace = "")
    public float sum(
        @WebParam(name = "a", targetNamespace = "")
        float a,
        @WebParam(name = "b", targetNamespace = "")
        float b
    );
}
