
package br.ufsc.das.wsclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2017-10-16T16:30:55.715-02:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "acceptOrderFault", targetNamespace = "http://das.ufsc.br/OrderProcess/")
public class AcceptOrderFault_Exception extends Exception {
    
    private br.ufsc.das.wsclient.AcceptOrderFault acceptOrderFault;

    public AcceptOrderFault_Exception() {
        super();
    }
    
    public AcceptOrderFault_Exception(String message) {
        super(message);
    }
    
    public AcceptOrderFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AcceptOrderFault_Exception(String message, br.ufsc.das.wsclient.AcceptOrderFault acceptOrderFault) {
        super(message);
        this.acceptOrderFault = acceptOrderFault;
    }

    public AcceptOrderFault_Exception(String message, br.ufsc.das.wsclient.AcceptOrderFault acceptOrderFault, Throwable cause) {
        super(message, cause);
        this.acceptOrderFault = acceptOrderFault;
    }

    public br.ufsc.das.wsclient.AcceptOrderFault getFaultInfo() {
        return this.acceptOrderFault;
    }
}
