package br.ufsc.das.productservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-23T11:20:27.685-02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "ProductService", 
                  wsdlLocation = "file:/D:/Work/workspace_devstudio/productService/src/ProductService.wsdl",
                  targetNamespace = "http://das.ufsc.br/ProductService/") 
public class ProductService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://das.ufsc.br/ProductService/", "ProductService");
    public final static QName ProductServiceSOAP = new QName("http://das.ufsc.br/ProductService/", "ProductServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Work/workspace_devstudio/productService/src/ProductService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Work/workspace_devstudio/productService/src/ProductService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSOAP")
    public ProductService getProductServiceSOAP() {
        return super.getPort(ProductServiceSOAP, ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSOAP")
    public ProductService getProductServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ProductServiceSOAP, ProductService.class, features);
    }

}
