package br.ufsc.das.productservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-23T11:20:27.649-02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://das.ufsc.br/ProductService/", name = "ProductService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebMethod(action = "http://das.ufsc.br/ProductService/product")
    @RequestWrapper(localName = "product", targetNamespace = "http://das.ufsc.br/ProductService/", className = "br.ufsc.das.productservice.Product")
    @ResponseWrapper(localName = "productResponse", targetNamespace = "http://das.ufsc.br/ProductService/", className = "br.ufsc.das.productservice.ProductResponse")
    @WebResult(name = "result", targetNamespace = "")
    public float product(
        @WebParam(name = "a", targetNamespace = "")
        float a,
        @WebParam(name = "b", targetNamespace = "")
        float b
    );
}
